### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pawansingh333** [Widiskel/drft-party-bot#1]
Error: Error Parsing Msg : not opened
    at WebSocket.<anonymous> (file:///C:/Users/Nomito/Desktop/New%20folder/drft-party-bot-master/src/core/drft.js:66:17)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at process.processTimers (node:internal/timers:519:7)
2024-08-12 23:04:16 [[31merror[39m]: unhandledRejection: Error Parsing Msg : not opened
Error: Error Parsing Msg : not opened
    at WebSocket.<anonymous> (file:///C:/Users/Nomito/Desktop/New%20folder/drft-party-bot-master/src/core/drft.js:66:17)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at process.processTimers (node:internal/timers:519:7)

**Comment by Widiskel** [comment]
check your node js version and make sure you follow all setup step correctly
