### ISSUE TITLE
Keeps reconnecting

### ISSUE THREAD

**Issue by GeeGeeCat** [Widiskel/drft-party-bot#11]
[2024-09-07T16:30:51.121] [WARN] - [Connection closed while receiving data]
Error: Not connected
    at ConnectionTCPFull.recv (C:\Users\cs\Desktop\drft-party-bot\node_modules\telegram\network\connection\Connection.js:71:15)
    at async MTProtoSender._recvLoop (C:\Users\cs\Desktop\drft-party-bot\node_modules\telegram\network\MTProtoSender.js:365:24)
[2024-09-07T16:30:52.135] [INFO] - [Started reconnecting]
[2024-09-07T16:30:52.135] [WARN] - [[Reconnect] Closing current connection...]
[2024-09-07T16:30:52.136] [INFO] - [Disconnecting from 91.108.56.110:80/TCPFull...]
[2024-09-07T16:30:52.137] [INFO] - [Connecting to 91.108.56.110:80/TCPFull...]
[2024-09-07T16:30:52.139] [INFO] - [Connection to 91.108.56.110:80/TCPFull complete!]
[2024-09-07T16:30:52.139] [INFO] - [Handling reconnect!]

[2024-09-07T16:30:53.210] [WARN] - [Disconnecting...]
[2024-09-07T16:30:53.210] [INFO] - [Disconnecting from 91.108.56.110:80/TCPFull...]
[2024-09-07T16:30:53.210] [WARN] - [Disconnecting...]
[2024-09-07T16:30:53.211] [INFO] - [Disconnecting from 91.108.56.110:80/TCPFull...]

**Comment by Widiskel** [comment]
this bot is deprecated already
