### ISSUE TITLE
Only WS Connected and then stuck bot not running

### ISSUE THREAD

**Issue by goldsfinder** [Widiskel/drft-party-bot#15]
2024-09-23 13:10:04 [[32minfo[39m]: 
2024-09-23 13:10:04 [[32minfo[39m]: Application Started
2024-09-23 13:10:04 [[32minfo[39m]: BOT STARTED
2024-09-23 13:10:04 [[32minfo[39m]: Log file cleared
2024-09-23 13:10:25 [[32minfo[39m]: Session undefined - Created
2024-09-23 13:10:29 [[31merror[39m]: {}
2024-09-23 13:10:29 [[31merror[39m]: {}
2024-09-23 13:10:29 [[32minfo[39m]: BOT STOPPED
2024-09-23 13:10:29 [[31merror[39m]: {}
2024-09-23 13:10:29 [[32minfo[39m]: BOT STARTED
2024-09-23 13:10:50 [[32minfo[39m]: Session andhika - Resolving Peer
2024-09-23 13:10:50 [[32minfo[39m]: Session andhika - Webview Connected
2024-09-23 13:10:51 [[32minfo[39m]: 245553722 - Try to Login...
2024-09-23 13:10:51 [[32minfo[39m]: GET : https://drftparty.fibrum.com/api/auth
2024-09-23 13:10:51 [[32minfo[39m]: Request Header : {"token":"query_id=AAE62qIOAAAAADraog7Yk9mA&user=%7B%22id%22%3A245553722%2C%22first_name%22%3A%22%F0%9F%90%A4%20Andhika%20%F0%9F%90%B0%20%F0%9F%90%88%F0%9F%90%A4%F0%9F%90%A5%F0%9F%90%A3%F0%9F%90%B9%22%2C%22last_name%22%3A%22Aristia%20%EF%B8%8F%EF%B8%8F%F0%9F%A6%B4%20%F0%9F%86%93%20%F0%9F%8D%85%20%F0%9F%9A%80PoPP%20%F0%9F%90%B0Gra-Gra%20%F0%9F%8C%B1SEED%22%2C%22username%22%3A%22Oxmarvelous%22%2C%22language_code%22%3A%22en%22%2C%22allows_write_to_pm%22%3Atrue%7D&auth_date=1727071850&hash=e3d9f65d1667419bced137aaaa092f87dc8bf721da13041aa890f282aff29572","Accept":"*/*","Accept-Language":"en-GB,en-US;q=0.9,en;q=0.8","Priority":"u=3, i","If-None-Match":"W/\"17f-+OPifTPvsOmXnCZBTm6WTMs0KCc\"","Sec-Fetch-Dest":"empty","Sec-Fetch-Site":"same-origin","Sec-Fetch-Mode":"cors","Sec-Ch-Ua":"Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 EdgiOS/125.2535.60 Mobile/15E148 Safari/605.1.15","User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 EdgiOS/125.2535.60 Mobile/15E148 Safari/605.1.15","Host":"drftparty.fibrum.com"}
2024-09-23 13:10:51 [[32minfo[39m]: Response : 200 OK
2024-09-23 13:10:51 [[32minfo[39m]: Response Data : {"user_tg_id":"245553722","user_nick":"Oxmarvelous","has_access":true,"payload":"","created_at":"1726553228","first_name":"🐤 Andhika 🐰 🐈🐤🐥🐣🐹","last_name":"Aristia ️️🦴 🆓 🍅 🚀PoPP 🐰Gra-Gra 🌱SEED","id":"873871","sessions_count":30,"total_drft_claims":1,"total_daily_claims":1,"last_claimed_task_id":101,"last_claim_task_time":"1726553312","last_claim_drft_time":"1726553306","last_login":"1727071085","wallet":null,"drft":"585"}
2024-09-23 13:10:52 [[32minfo[39m]: 245553722 - Successfully Login
2024-09-23 13:10:53 [[32minfo[39m]: 245553722 - Connecting to WSS...
2024-09-23 13:10:53 [[31merror[39m]: unhandledRejection: Error Parsing Msg : Unexpected token w in JSON at position 0
Error: Error Parsing Msg : Unexpected token w in JSON at position 0
    at WebSocket.<anonymous> (file:///D:/bot-telegram/DriftParty/bot1/multi3/src/core/drft.js:72:17)
    at WebSocket.emit (node:events:517:28)
    at _receiver.onmessage (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\WebSocket.js:146:54)
    at Receiver.dataMessage (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\Receiver.js:139:10)
    at TLSSocket.<anonymous> (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\WebSocket.js:142:22)
    at TLSSocket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
2024-09-23 13:10:53 [[31merror[39m]: unhandledRejection: Error Parsing Msg : Unexpected token w in JSON at position 0
Error: Error Parsing Msg : Unexpected token w in JSON at position 0
    at WebSocket.<anonymous> (file:///D:/bot-telegram/DriftParty/bot1/multi3/src/core/drft.js:72:17)
    at WebSocket.emit (node:events:517:28)
    at _receiver.onmessage (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\WebSocket.js:146:54)
    at Receiver.dataMessage (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\Receiver.js:139:10)
    at TLSSocket.<anonymous> (D:\bot-telegram\DriftParty\bot1\multi3\node_modules\ws\lib\WebSocket.js:142:22)
    at TLSSocket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)

**Comment by ShmilyGone** [comment]
Me too, same error.

**Comment by Widiskel** [comment]
bot its deprecated already
