### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Sezmund** [Widiskel/drft-party-bot#3]
Error During executing bot TypeError: Cannot read properties of undefined (reading 'message')
    at operation (file:///C:/Users/user/Desktop/suka%20rabotai/drft-party-bot/index.js:31:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/user/Desktop/suka%20rabotai/drft-party-bot/index.js:78:9
    at async Promise.all (index 0)
    at async file:///C:/Users/user/Desktop/suka%20rabotai/drft-party-bot/index.js:81:7
[2024-08-17T19:08:46.262] [INFO] - [Running gramJS version 2.22.1]
[2024-08-17T19:08:46.265] [INFO] - [Connecting to 149.154.167.41:80/TCPFull...]

C:\Users\user\Desktop\suka rabotai\drft-party-bot>

Status : WSS Connection Closed...
Delay : Delaying for 0 Hours 0 Minutes 1 Seconds

**Comment by copycatcodex** [comment]
I also get the same error.

**Comment by MuscleeMuseum** [comment]
Same problem

**Comment by Widiskel** [comment]
go pull new update
