### ISSUE TITLE
Unexpected token G in JSON at position 0

### ISSUE THREAD

**Issue by MzTechnology97** [Widiskel/drft-party-bot#9]
2024-09-06 15:18:25 [[32minfo[39m]: 359373192 - Successfully Login
2024-09-06 15:18:26 [[32minfo[39m]: 359373192 - Connecting to WSS...
2024-09-06 15:18:26 [[31merror[39m]: unhandledRejection: Error Parsing Msg : Unexpected token G in JSON at position 0
Error: Error Parsing Msg : Unexpected token G in JSON at position 0
    at WebSocket.<anonymous> (file:///root/drft-party-bot/src/core/drft.js:72:17)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/root/drft-party-bot/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:517:28)
    at Receiver.dataMessage (/root/drft-party-bot/node_modules/ws/lib/receiver.js:596:14)
    at Receiver.getData (/root/drft-party-bot/node_modules/ws/lib/receiver.js:496:10)
    at Receiver.startLoop (/root/drft-party-bot/node_modules/ws/lib/receiver.js:167:16)
    at Receiver._write (/root/drft-party-bot/node_modules/ws/lib/receiver.js:94:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
2024-09-06 15:18:26 [[31merror[39m]: unhandledRejection: Error Parsing Msg : Unexpected token G in JSON at position 0
Error: Error Parsing Msg : Unexpected token G in JSON at position 0
    at WebSocket.<anonymous> (file:///root/drft-party-bot/src/core/drft.js:72:17)
    at WebSocket.emit (node:events:517:28)
    at Receiver.receiverOnMessage (/root/drft-party-bot/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:517:28)
    at Receiver.dataMessage (/root/drft-party-bot/node_modules/ws/lib/receiver.js:596:14)
    at Receiver.getData (/root/drft-party-bot/node_modules/ws/lib/receiver.js:496:10)
    at Receiver.startLoop (/root/drft-party-bot/node_modules/ws/lib/receiver.js:167:16)
    at Receiver._write (/root/drft-party-bot/node_modules/ws/lib/receiver.js:94:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)

**Comment by Widiskel** [comment]
bot is now unmaintable
